image: node:lts-alpine

variables:
  ENVIRONMENT: $CI_COMMIT_BRANCH


# test-job:
#   stage: test
#   script:
#     - echo "This job tests something"


deploy-static-site:
  stage: deploy
  before_script:
    - apk add --no-cache autoconf automake libtool build-base nasm pkgconf
    - echo here
    - pwd
    - ls -alth
    - npm ci
    - npm run build
  script:
    - cd serverless/s3
    - echo later
    - echo ls -alth
    - npm ci
    - ENVIRONMENT="$ENVIRONMENT" npm run sls:deploy
