image: node:lts-alpine

variables:
  ENVIRONMENT: $CI_COMMIT_BRANCH

deploy:
  stage: deploy
  before_script:
    # required to install these dependencies not included in node:lts-alpine image after introducing 1909033e
    # which included the following js deps "gatsby-plugin-image", "gatsby-plugin-sharp", "gatsby-source-filesystem", "gatsby-transformer-sharp"
    - apk add --no-cache autoconf automake libtool build-base nasm pkgconf
    - npm ci
    - npm run build
    - echo "$AWS_ACCESS_KEY_ID"
    - export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
    - export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
    - export AWS_DEFAULT_REGION=ap-southeast-1
  script:
    - echo $AWS_ACCESS_KEY_ID
    - cd serverless/cdk
    - npm ci
    - npm run deploy:dev
    - aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DIST_ID"  "/index.html"

