image: node:lts-alpine

variables:
  ENVIRONMENT: $CI_COMMIT_BRANCH


# test-job:
#   stage: test
#   script:
#     - echo "This job tests something"


deploy:
  # only:
  #   refs:
  #     - dev
  stage: deploy
  before_script:
    - npm ci
    - npm run build
  script:
    - ls -alth
    - ENVIRONMENT="$ENVIRONMENT" serverless client deploy --no-confirm 