image: node:lts-alpine

variables:
  ENVIRONMENT: $CI_COMMIT_BRANCH

deploy:
  stage: deploy
  before_script:
    - chmod 755 ./ci-script/setup.sh
    - ./ci-script/setup.sh  
    - npm ci
    - npm run build
    - echo "$AWS_ACCESS_KEY_ID"
    - export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
    - export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
    - export AWS_DEFAULT_REGION=ap-southeast-1
  script:
    - echo $AWS_ACCESS_KEY_ID
    - cd serverless/cdk
    - npm ci
    - npm run deploy:dev
    - aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DIST_ID" --paths "/*"

