image: node:lts-alpine

variables:
  ENVIRONMENT: $CI_COMMIT_BRANCH

# test-job:
#   stage: test
#   script:
#     - echo "This job tests something"

deploy:
  stage: deploy
  before_script:
    # required to install these dependencies not included in node:lts-alpine image after introducing 1909033e
    # which included the following js deps "gatsby-plugin-image", "gatsby-plugin-sharp", "gatsby-source-filesystem", "gatsby-transformer-sharp"
    - apk add --no-cache autoconf automake libtool build-base nasm pkgconf
    - npm ci
    - npm run build
    - echo "$AWS_ACCESS_KEY_ID"
    - export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
    - export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
    - export AWS_DEFAULT_REGION=ap-southeast-1
  script:
    - echo $AWS_ACCESS_KEY_ID
    - cd serverless/cdk
    - npm ci
    - npm run deploy:dev

# deploy-api:
#   stage: deploy
#   before_script:
#     - cd serverless/api
#     - npm ci
#   script:
#     - ENVIRONMENT="$ENVIRONMENT" npm run sls:deploy
