image: node:lts-alpine

variables:
  ENVIRONMENT: $CI_COMMIT_BRANCH


# test-job:
#   stage: test
#   script:
#     - echo "This job tests something"


deploy-static-site:
  stage: deploy
  before_script:
    - npm ci
    - npm run build
  script:
    - cd serverless/s3
    - npm ci
    - ENVIRONMENT="$ENVIRONMENT" npm run sls:deploy