image: node:lts-alpine

stages:
  - build
  -  deploy

variables:
  ENVIRONMENT: $CI_COMMIT_BRANCH

default:
  before_script:
    - npm ci

build-job:
  stage: build
  script:
    - npm run build

# test-job:
#   stage: test
#   script:
#     - echo "This job tests something"


deploy:
  # only:
  #   refs:
  #     - dev
  stage: deploy
  script:
    - ls -alth
    - ENVIRONMENT="$ENVIRONMENT" npm run sls -- deploy