# https://www.serverless.com/blog/node-rest-api-with-serverless-lambda-and-dynamodb

service: bickup-apis

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${env:ENVIRONMENT} # takes in an environment variable named 'ENVIRONMENT'
  region: ap-southeast-1

functions:
  jobSubmission:
    handler: job.submit
    memorySize: 128
    description: Submit job information
    events:
      - http: 
          cors: true
          path: job
          method: post

# https://www.serverless.com/framework/docs/providers/aws/guide/resources/
# resources:
#   Resources:
#     jobsTable:
#       Type: AWS::DynamoDB::Table
#       Properties:
#         TableName: jobsTable
#         AttributeDefinitions:
#           - AttributeName: xxx
#             AttributeType: S
#         KeySchema:
#           - AttributeName: clientNumber # client hp number
#             KeyType: HASH
#           - AttributeName: timestamp # timestamp of job submission
#             KeyType: RANGE
        