# https://www.serverless.com/blog/node-rest-api-with-serverless-lambda-and-dynamodb

service: bickup-apis

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${env:ENVIRONMENT} # takes in an environment variable named 'ENVIRONMENT'
  region: ap-southeast-1

functions:
  jobSubmission:
    handler: job.submit
    memorySize: 128
    description: Submit job information
    events:
      - http: 
          cors: true
          path: job
          method: post